FROM openresty/openresty:alpine-fat
COPY nginx_lua/ /opt/app/
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf
COPY index.html /usr/local/openresty/nginx/html/index.html
COPY index.css /usr/local/openresty/nginx/html/index.css
