version: "3"
services: 
  imagebuild:
    image: dalongrong/rrweb-demo
    build: 
      context: ./
      dockerfile: ./Dockerfile-build
  app: 
   image: openresty/openresty:alpine-fat
   ports:
   - "8080:8080"
   volumes:
   - "./nginx_lua/:/opt/app/"
   - "./index.html:/usr/local/openresty/nginx/html/index.html"
   - "./nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf"